ocaml/omd

- opam
- src/omd_utils.ml
`id_of_string`, which is used to come up with the `id` attributes for headers in the HTML backend, does not handle non-alphanumeric characters as its comments describe.
I've written a replacement that does what I think `id_of_string` is intended to do, and made a file with some example cases for comparison.
```ocaml
let old_id_of_string s =
let l = String.length s in
let gen_id s =
let b = Buffer.create l in
let rec loop i flag flag2 =
(* [flag] prevents trailing dashes;
[flag2] prevents IDs from starting with dashes *)
if i = l then
()
else
match s.[i] with
| 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' as c ->
(if not (flag2 || flag) then Buffer.add_char b '-');
Buffer.add_char b c;
loop (i+1) true true
| _ ->
if flag2 || flag then
loop (i+1) false flag2
else
(Buffer.add_char b '-';
loop (i+1) …
```
> Fix id_of_string to handle special characters as described.

- .gitattributes
Just a little PR for the sake of clarity:
git-linguist detects the dune.inc files as php files, distorting the stats of the project, making it shown as mainly coded in php (~44,7% of php).
Kinda funny considering the "pure ocaml" mention :p
This pull-request does not change directly the language of .inc files, but as dune.inc files are auto-generated, it adds a git attribute, telling linguist to ignore those files
> Corrected linguist language detection

- src/ast.ml
- src/block.ml
- src/block.mli
- src/html.ml
- src/markdown.ml
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
- src/text.ml
This pull request is part of the work needed for this [issue](https://github.com/ocaml/omd/issues/175):
In order to modify the behaviour of omd from the user, I added a printer record, containing the printing functions.
It allows the user to redefine their behaviour by creating a new record with the new functions, then give it as an argument for the to_html function.
For example, the following code wraps the headings in a section (ugly code, could be better, just for example):
```ocaml
let printer =
let headings = ref [] in
in
let print_heading (p: Omd.printer) b (i, md) =
let f j =
if i <= j
then
(Buffer.add_string b (Printf.sprintf "</section>\n"); false)
else
true in
headings := i::(List.filter f !headings);
let id = Buffer.create 64 in
Buffer.add_string b (Printf.sprintf …
```
> Added printer implementation for dumping modifications from the user

- src/ast.ml
- src/block.ml
- src/html.ml
- src/markdown.ml
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
- src/text.ml
- tests/tag/dune
- tests/tag/tag.html
- tests/tag/tag.md
- tests/tag/tag_uppercase.html
- tests/tag/tag_uppercase.md
- tests/tag/uppercase.ml
This pull request contains the implementation of the tag extension system discussed [here](https://github.com/ocaml/omd/issues/190):
It allows the user to use self defined printers by using a new syntax:
For inline tags:
```
This is an {!foo: inline tag}.
```
For tag blocks:
```
{!bar:
This is a tag block
}
```
The html tag printers will be called with an object containing:
- the string of the tag (in the examples, it will be `bar`)
- in the case of an inline tag, the text (`inline tag` for the example)
- in the case of a tag block, the list of the blocks contained in the tag (here, a Paragraph).
- and finally the attributes
Nesting blocks inside a tag block is possible !
This implementation may need some corrections, I'm listening to all your comments and modifications requests :)
> Added implementation of inline tags and tag blocks

- src/ast.ml
- src/block.ml
- src/html.ml
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
- tests/def_list/def_list.html
- tests/def_list/def_list.md
- tests/def_list/dune
This pull request adds the implementation of definition lists in markdown files.
This feature is not part of the commonmark specification, but was requested in [this issue](https://github.com/ocaml/omd/issues/188) as being a part of the [extended markdown syntax](https://www.markdownguide.org/extended-syntax).
The syntax of definition lists is pretty easy:
```
First Term
: This is the definition of the first term.
Second Term
: This is one definition of the second term.
: This is another definition of the second term.
```
The parsing is dumb, but works actually pretty well:
Lines of raw text beginning are considered as `Ldef_list` tokens, and if during the process of the blocks, they are preceded by one single line of raw text or an already created definition list block, a definition list …
> Implementation of definition lists

- src/ast.ml
- src/block.ml
- src/block.mli
- src/dune
- src/html.ml
- src/markdown.ml
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
- src/text.ml
- tests/tag/uppercase.ml
See #198 
- Do not leak type variable in main types
- Flatten type hierarchy
- Cleanup public API (`omd.mli`)
> Cleanup main type signature

- src/ast.ml
- src/block.ml
- src/html.ml
- src/html.mli
- src/omd.mli
- src/parser.ml
Simplify the representation for attributes, share the type with the HTML backend.
> Lighter representation for attributes

- src/ast.ml
- src/block.ml
- src/block.mli
- src/html.ml
- src/html.mli
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
Various clean ups of the AST.
- Attach attributes generically to AST nodes
- Get rid of various auxiliary record types
- Get rid of fields in the AST nodes not relevant for conversion into other formats
> Simplify ast

- src/ast.ml
- src/block.ml
- src/block.mli
- src/html.ml
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
As [observed](https://github.com/ocaml/omd/issues/216#issuecomment-653841374) by @shonfeder, the `Link_def` node is no longer useful in the AST. Let's remove it.
> Get rid of Link_def node

- dune-project
- omd.opam
The code uses String.split_on_char which was introduced in 4.04.
Should I also regenerate the opam file?
> dune-project: add lower bound on ocaml

- src/ast.ml
- src/block.ml
- src/block.mli
- src/html.ml
- src/html.mli
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
Opening the PR to continue the discussion started on #228.
Changes to the AST are:
* Remove the record wrapper for each node and inline the attribute field
* Make the block type parametric with the goal of using this flexibility to later have a way to parse and return the AST with source locations and whatever information we might want per node.
> AST representation changes

- .github/workflows/workflow.yml
- .ocamlformat
- Makefile
- bin/main.ml
- src/ast.ml
- src/block.ml
- src/block.mli
- src/compat.ml
- src/dune
- src/html.ml
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
- src/toc.ml
- tests/dune
- tests/extract_tests.ml
- tests/omd.ml
- tools/gen_entities.ml
- Add an `.ocamlformat` config
- Reformat code base
- CI pipeline updates
- Use github actions v2
- Run formatting check
- Add missing compiler versions
- Enable dune-cache
I'll wait to merge this until #232 (and other substantial outstanding PRs?) are merged in.
In the meantime, @sonologico, whenever you have a chance, let me know if you are OK with these formatting, or if you have strong feelings by a different config.
> Add ocamlformat and update CI pipeline

- .ocamlformat
- README.md
- src/sexp.ml
- src/toc.ml
This is a preview of the not-yet-released `ocamlformat.0.19.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
> Upgrade to ocamlformat.0.19.0

- dune-project
- tests/blackbox/dune
- tests/blackbox/regression-224.t
Closes #224 
This also bumps our dune lang version up to 2.7, which reverses course from #218,  originally motivated by #212.
See  c3d151e for the rationale. 
This bears upon one aspect of the testing question that came up at #248. @sonologico how do you feel about adopting Dune's built in support for cram-style tests, as I'm doing here, for our end-to-end testing setup?
> Add regression test for #224

- CHANGES.md
- bin/main.ml
I've been working on something that uses the `omd` binary to provide a text-only version of the markdown as a standalone html page and noticed `omd x y z` outputs HTML to `stdout` in the order `z y x`, I tried `omd.1.3.1` and it outputs the HTML in the same order the files were given which I think is the more expected behaviour.
> Preserve order of input file list

- src/parser.ml
- tests/dune.inc
- tests/extract_tests.ml
I'll double check if my intuition is correct, but this fixes the test.
What was happening is that we would process the inline content of the (would be) label and use the results even if it didn't turn out to be a label. However, because one `*` was between brackets and the other `*` was outside, they were never matched and therefore treated as text.
> Fix spec 519. Reprocess inlines in case a label turns out to not be for a link

- src/compat.ml
- src/parser.ml
- tests/dune.inc
- tests/extract_tests.ml
> Spec 334: Preserve spaces in inline code blocks consisting of spaces only

- .github/workflows/workflow.yml
- Makefile
- README.md
- bin/dune
- bin/main.ml
- dune-project
- omd.opam
See https://github.com/ocaml/omd/issues/253.
This (currently draft) PR adds a `--version` flag to the `omd` CLI program. It's using the [`dune-build-info`](https://dune.readthedocs.io/en/latest/dune-libs.html#dune-build-info-library) library to extract the version from `dune-project` to avoid needing another place to track the version.
I'm open to feedback here, because on the one hand this seems convenient (i.e. not having to re-define the version in code since it's already in `dune-project`) but on the other it might be preferable to keep this library dependency-free.
Changes:
> add `--version` flag to cli (closes #253)

- .ocamlformat
- bin/main.ml
- src/ast.ml
- src/block.ml
- src/compat.ml
- src/html.ml
- src/html.mli
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
- src/toc.ml
- tests/extract_tests.ml
- tests/omd.ml
Removed deprecated options and options for which we had deprecated values. I'm open to other choices options on `.ocamlformat` file
> Ocamlformat 0.21.0

- .github/workflows/workflow.yml
Seems our window builds on failing on 4.04.2 on the new setup-ocaml release. Seeing if rolling back to the last patch fixes the problem.
> Pin setup-ocaml at v2.0.3

- .github/workflows/workflow.yml
- dune-project
- omd.opam
Addresses https://github.com/ocaml/camlp-streams/issues/7 breaking our CI pipeline by bumping the minimum required OCaml version to 4.05.
Also see https://github.com/ocaml/omd/pull/275#issuecomment-1201523735
> Bump min ocaml version to 4.05

- src/omd.ml
- src/omd.mli
Fixes: #252
Not sure if all the constructors make sense. Open to suggestions, also regarding the functions' names.
> add constructors for values of type `Omd.doc`

- dune-project
- omd.opam
- src/dune
- src/parser.ml
- tests/blackbox/normalize-label.t
- tests/dune.inc
- tests/extract_tests.ml
Input:
```
[ẞ]
[SS]: /url
```
This is the result in master:
```diff
File "tests/spec-539.html", line 1, characters 0-0:
diff --git a/_build/default/tests/spec-539.html b/_build/default/tests/spec-539.html.new
index c31102f..4e28a6f 100644
--- a/_build/default/tests/spec-539.html
+++ b/_build/default/tests/spec-539.html.new
@@ -1 +1 @@
-<p><a href="/url">ẞ</a></p>
+<p>[ẞ]</p>
make: *** [test] Error 1   
```
The issue is that both labels are not being matched, hence is it not recognized as a link. To match labels, we need to `normalize` them (strip off leading/trailing whitespace, ...) and do a case-insensitive comparison. The unicode version of that is a bit more complex as we need to do a `Unicode case folding`. From the spec:
>  One label …
> unicode link label normalization (fix test 539)

- src/parser.ml
- tests/dune.inc
- tests/extract_tests.ml
Input:
```
[ΑΓΩ]: /φου
[αγω]
```
The current result in master:
```diff
File "tests/spec-206.html", line 1, characters 0-0:
diff --git a/_build/default/tests/spec-206.html b/_build/default/tests/spec-206.html.new
index 93c6540..97ea23b 100644
--- a/_build/default/tests/spec-206.html
+++ b/_build/default/tests/spec-206.html.new
@@ -1 +1,2 @@
-<p><a href="/%CF%86%CE%BF%CF%85">αγω</a></p>
+<p>[ΑΓΩ]: /φου</p>
+<p>[αγω]</p>
```
There are two issues here:
1. Labels are not being matched, hence it is not recognized as a link. This is what I fixed in https://github.com/ocaml/omd/pull/277. I included that change in the first commit.
2. The url destination is not percent encoded. From the spec:
> A [link destination](https://spec.commonmark.org/0.30/#link-destination) consists of either
> 
> * a …
> fix test 206

- src/block.ml
- tests/dune.inc
- tests/extract_tests.ml
```md
[foo]: /url
bar
===
[foo]
```
Current result:
```
<h1>[foo]: /url                     
bar</h1>
<p>[foo]</p>
```
Expected result:
```
<h1>bar</h1>
<p><a href="/url">foo</a></p>
```
The issue is that when parsing a `Lsetext_heading` (===), we were wrapping all the `Rparagraph` lines in a `Heading`, without taking into account that some of the `lines` might be a `link reference definition`
```
[foo]: /url
===
[foo]
```
Current result:
```
<h1>[foo]: /url</h1>                
<p>[foo]</p>
```
Expected result:
```
<p>===
<a href="/url">foo</a></p>
```
Same as 216 except that in that case there's nothing between the `link reference definition` and the `Lsetext_heading`. There's nothing then to make as `Heading`.
> fix 215 and 216

- src/ast.ml
- src/ast_block.ml
- src/ast_inline.ml
- src/block.mli
- src/block_parser.ml
- src/block_parser.mli
- src/html.ml
- src/html.mli
- src/omd.ml
- src/omd.mli
- src/parser.ml
- src/sexp.ml
- src/toc.ml
This aims to improve the organization of the Ast module. The key changes:
- Avoid duplication of types by use of `module include type of`
- Break up Inline types and Block types into seperate modules
- Improve naming on block type funtors
- Correct name of `Block` module to `Block_parser`, cause it's a parser,
not a representation of blocks
This was spun out of work on #288 and is a pre-requisite for the changes there, as it allows sharing the high-level `doc` type.
> Restructure Ast module

- README.md
Closes #274
In addition to linking the docs and giving instructions for building them
locally, this small changeset also includes some light restructuring of the
README.
> Add instructions for building and viewing docs

- .github/workflows/workflow.yml
- dune-project
- omd.opam
- src/ast_constructors.ml
- src/omd.ml
- src/omd.mli
- tests/dune
- tests/expect_tests.ml
Followup to #268.
These changes expand and rework the constructors for AST values proposed 
in #252. The aim is to make construction of AST values relatively simple
and light weight.
The constructors lacked some ergonomic convenience, and we were missing
a constructor for headings and missing a way to construct elements that
included concatenated inlines (so, e.g., there was no way of constructing
a paragraph that would include mixing plain text with `em` or `strong` text.
I think this was mostly due to us having omitted  tests that
would show how the constructors were meant to be used when we first
introduced them, so I'm adding in tests as I go so we can see how usage
will look, and spot any irregularities or oversights.
> Rework element constructors

- CHANGES.md
- README.md
- src/ast.ml
- src/ast_block.ml
- src/block_parser.ml
- src/html.ml
- src/html.mli
- src/parser.ml
- src/sexp.ml
- src/strSlice.ml
- src/strSlice.mli
- src/toc.ml
- tests/dune
- tests/dune.inc
- tests/extra_table_tests.md
- tests/gfm_table_spec.md
First cut of support for GitHub-Flavoured Markdown (GFM) tables. No tests yet, but I thought I'd submit a preliminary pull request to make sure that there was interest. This handles simple tables that always have headers, and only allow inline content in cells, and no multi-column or multi-row cells.
All of the existing tests pass.
Addresses part of issue #205 .
GFM-style tables are documented here: https://github.github.com/gfm/#tables-extension- . The code so far seems to work for all the examples in that document, but I haven't made a proper test suite yet, mostly because I don't yet understand how the testing works. I've noticed that there are a few differences between the GFM documentation and Pandoc's `gfm` implementation too.
I added some functions to the `StrSlice` module to make …
> Support for GitHub-Flavoured Markdown tables

- CHANGES.md
- bin/main.ml
- src/html.ml
- src/html.mli
- src/omd.ml
- src/omd.mli
- tests/blackbox/heading-id.t
- tests/expect_tests.ml
- tests/omd.ml
Fixes: #251
add an --auto-identifiers boolean option
(Resolution of merge conflics)
Authored by @tatchi in #267, but reworked in this new branch to ease resolution of merge conflicts.
> Automatically fill the id attributes of headings

- src/html.mli
- src/omd.ml
- src/omd.mli
Expose escape_html_entities which escapes meaningful HTML characters
in order to prevent them from being interpreted.
This is needed by Hilite. See issue
https://github.com/ocaml/ocaml.org/issues/496
> Expose HTML escape function
